// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xdcxuiceiarbspvozgpl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhkY3h1aWNlaWFyYnNwdm96Z3BsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTgxNjIyOTksImV4cCI6MjA3MzczODI5OX0.TxLvnljrgW9cQbKuadXI3pEXGEF9rHZSdUXlcbpWbhA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});